[project]
name = "pytorch-test"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "torch>=2.2",
    "numpy>=1.24",
    "imageio>=2.34",
    "imageio-ffmpeg>=0.4.9",
]

[tool.rats-devtools]
enabled = true
